---
defaults:
  # The first entry here always has to be the name we have passed to `register_hydra_config`.
  - config_schema
  # Then we have to choose defaults for the config groups.
  - dm: cmnist
  - model: fcn
  # For subconfigs that aren't config groups, we can just set `null` here and hydra
  # then uses the default values from the dataclass.
  - opt: null
