---
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v3
      - name: Lint with ruff
        run: |
          rye lint -- --output-format=github
      - name: Format with ruff
        run: |
          rye fmt -- --diff .
